# Generated by Django 6.0 on 2025-12-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo_url', models.URLField(blank=True)),
                ('experiense_years', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_activ', models.BooleanField(default=True)),
            ],
        ),
    ]
