# Generated by Django 5.1.7 on 2025-12-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидание'), ('confirmed', 'Подтвержденно'), ('canceled', 'Отмененно'), ('completed', 'Выполненно'), ('no_show', 'Не явился')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
