# Generated by Django 5.1.7 on 2025-12-14 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_add_barber_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='photo_url',
        ),
    ]
